# Generated by Django 5.1 on 2024-09-13 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lake', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boat_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('open', models.BooleanField(default=True)),
                ('available_to_customers', models.BooleanField(default=True)),
                ('issues', models.TextField()),
                ('rules', models.TextField()),
                ('image', models.ImageField(default='..static/images/dbc-logo-small.png', upload_to='')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boats', to='boats_and_locations.marina')),
            ],
        ),
    ]
