# Generated by Django 5.1 on 2024-09-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marina',
            name='description',
        ),
        migrations.AlterField(
            model_name='marina',
            name='lake',
            field=models.TextField(default='Unkown'),
        ),
    ]
