# Generated by Django 5.1 on 2024-11-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0002_remove_marina_description_alter_marina_lake'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='image',
            field=models.ImageField(default='..static/images/dbc-logo-small.png', upload_to=''),
        ),
    ]
