# Generated by Django 5.1 on 2024-11-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0003_marina_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='state',
            field=models.TextField(default='Unknown', max_length=100),
        ),
    ]
