# Generated by Django 5.2.3 on 2025-10-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0004_marina_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
