# Generated by Django 5.2.3 on 2025-10-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0005_marina_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='available_to_customers',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='marina',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='open',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='rules',
        ),
        migrations.AddField(
            model_name='boat',
            name='images',
            field=models.ImageField(default='..static/images/', upload_to=''),
        ),
        migrations.AddField(
            model_name='boat',
            name='length',
            field=models.CharField(default=20, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boat',
            name='max_hp',
            field=models.CharField(default=150, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boat',
            name='passengers',
            field=models.CharField(default=10, max_length=2),
            preserve_default=False,
        ),
    ]
