# Generated by Django 5.2.3 on 2025-10-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0006_rename_image_boat_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='max_hp',
            field=models.CharField(max_length=10),
        ),
    ]
