# Generated by Django 5.2.3 on 2025-10-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0007_alter_boat_max_hp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='main_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='images',
        ),
    ]
