# Generated by Django 5.2.3 on 2025-10-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0008_rename_main_image_boat_image_remove_boat_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='checkfront_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
