# Generated by Django 5.2.3 on 2025-12-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0010_alter_marina_address_alter_marina_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marina',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marina',
            name='image',
            field=models.ImageField(blank=True, default='..static/images/dbc-logo-small.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='marina',
            name='lake',
            field=models.TextField(blank=True, default='Unkown', null=True),
        ),
        migrations.AlterField(
            model_name='marina',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marina',
            name='state',
            field=models.TextField(blank=True, default='Unknown', max_length=100, null=True),
        ),
    ]
