# Generated by Django 5.2.3 on 2025-12-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0011_alter_marina_address_alter_marina_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='marinas',
            field=models.ManyToManyField(blank=True, related_name='boats', to='boats_and_locations.marina'),
        ),
    ]
