# Generated by Django 5.2.3 on 2026-01-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0012_boat_marinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marina',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marinas/'),
        ),
    ]
