# Generated by Django 5.2.3 on 2026-01-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0013_alter_marina_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
