# Generated by Django 5.2.3 on 2026-01-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0014_marina_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
