# Generated by Django 5.2.3 on 2026-03-17 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0015_boat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='restaurant_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='restaurant_image',
            field=models.ImageField(blank=True, null=True, upload_to='marina_restaurants/'),
        ),
        migrations.AddField(
            model_name='marina',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marina',
            name='lake',
            field=models.TextField(blank=True, default='Unknown', null=True),
        ),
        migrations.CreateModel(
            name='MarinaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marina_photos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='boats_and_locations.marina')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
