# Generated by Django 5.2.3 on 2026-03-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0016_marina_description_marina_restaurant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='extra_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='extra_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
