# Generated by Django 5.2.3 on 2026-03-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0017_marina_extra_description_marina_extra_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='feature_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='marina_features/'),
        ),
        migrations.AddField(
            model_name='marina',
            name='feature_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
