# Generated by Django 5.2.3 on 2026-03-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0018_marina_feature_description_marina_feature_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marina',
            name='extra_description',
        ),
        migrations.RemoveField(
            model_name='marina',
            name='extra_title',
        ),
        migrations.AddField(
            model_name='marina',
            name='display_states',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
