# Generated by Django 5.2.3 on 2026-04-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0019_remove_marina_extra_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom')], default='middle', max_length=10),
        ),
    ]
