# Generated by Django 5.2.3 on 2026-04-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0020_boat_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marina',
            old_name='image',
            new_name='hero_image',
        ),
        migrations.AddField(
            model_name='marina',
            name='carousel_image',
            field=models.ImageField(blank=True, null=True, upload_to='marina_carousel/'),
        ),
    ]
