# Generated by Django 5.2.3 on 2026-05-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0021_rename_image_marina_hero_image_marina_carousel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
