"""
Django settings for boatclub project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import mimetypes
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z$qd=(8%%)!l8$#6ka^*_iekp)kxs57=076n2%lxpcl55=f81-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.herokuapp.com', 'localhost','127.0.0.1','destinationboatclub.com','www.destinationboatclub.com',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'reservations',
    'boats_and_locations',
    'users',
    'pdf_form',
    'docusign',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'boatclub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'boatclub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Default: use SQLite locally
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# If a DATABASE_URL is set (like on Heroku), use Postgres instead
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        ssl_require=True
    )


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/users/login/'
# Redirect after login
LOGIN_REDIRECT_URL = '/'

# Redirect after logout
LOGOUT_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.aol.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'testconfemail@aol.com'

EMAIL_HOST_PASSWORD = 'Hockey83*!'

#SENDGRID RECORVERY CODE: KMLTT6XTNRD9ZA4SWXLS7199 sendgrid account:joe4a83@gmail.com
#SENDGRID API NAME: dbctest
#SENDGRID API KEY : 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

#SENDGRID_API_KEY = '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'

mimetypes.add_type("application/javascript", ".mjs", strict=True)


#Docusign RSA Public key: -----BEGIN PUBLIC KEY-----
# MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsPt+snvLhrXxDfTF3A+B
# EdkR2dlAcfEIk715kNKHwWufgIvQ7QNodKOYtJdrZmT3AN3u6R4+fCHKfLEEhEfN
# 97F83S0GcB0YFuI7Mp2MUN4IpZzCUzTJCBtDZWIY495CiWogzOqF4kpYKAil/E7o
# 5MlXqChctCKVMoydGDjj04J1NIFfGznBFesXCpRVX6AAwi95U2piMe759cufm2TQ
# SSAN7LSOZOitO6tokbQZ7XdlLaBW6TuK8WC6tIS3jKQ22m0mpJ14FgDM0YU0W8Pv
# nYWr9cICh5wk398gGIB4l6uIJa6rHxSxAUVWBkHEMyb+W+ftCpskvC+w9LJCe0Lx
# bQIDAQAB
# -----END PUBLIC KEY-----

#docusign RSA Private Key:-----BEGIN RSA PRIVATE KEY-----
# MIIEpAIBAAKCAQEAsPt+snvLhrXxDfTF3A+BEdkR2dlAcfEIk715kNKHwWufgIvQ
# 7QNodKOYtJdrZmT3AN3u6R4+fCHKfLEEhEfN97F83S0GcB0YFuI7Mp2MUN4IpZzC
# UzTJCBtDZWIY495CiWogzOqF4kpYKAil/E7o5MlXqChctCKVMoydGDjj04J1NIFf
# GznBFesXCpRVX6AAwi95U2piMe759cufm2TQSSAN7LSOZOitO6tokbQZ7XdlLaBW
# 6TuK8WC6tIS3jKQ22m0mpJ14FgDM0YU0W8PvnYWr9cICh5wk398gGIB4l6uIJa6r
# HxSxAUVWBkHEMyb+W+ftCpskvC+w9LJCe0LxbQIDAQABAoIBACBJKNI/kh/XhguB
# OS0NaQLMAh0nLEH88g8dlBUuytQmoXjOSMVMB1yr0Xo0W0PZLFQsqF4/ha+YbHt1
# wXiuLq0+ZCRnB9MhA5l9GMaBhizkbFhl8e9C5F+FtbRDgn3jOGkgAq7PI7Bl1pIr
# Dbiq3oKKFmMXRd4YpvYLP8dA7ZLSXa6mcdOVk3GprbF6VasXB2KUGQf8qs/Rk6vT
# IRXdi1lpsbji8ck/jrj+l+H2Wqj40IA9HUmr8PoflB7xy91mgTLTwPTryXVC4rVs
# E3w5qNDkDuAkdYr2Vl/6b+0lcKp6iz6DDVaLr0AqeXzHQmTc/3WR3hDn/qKm+kCS
# DNpcXQMCgYEA9ymrQ/kKnEE9eKHqdn3vsaB06Dtb/9d5py2Zc6jZUDXm2/ecPFUj
# Ajvw1QOVdjXX1KEuqv+FqXLzr6F0nuG7KkkmEQmQqWUzYXSvgJS1jDcJ4uouLuBy
# lhDPN3fFn1zWJVhV3FHgQAb8GqjhgMgwNnNz829o7aJuTXO0dsfCvbMCgYEAt09z
# ZM2uTYVENPrZBLK3NF0QWAb27kvuoHK4eWs5bm6RuSUexdYOtRrJqg8KbFu95Xhr
# r6SxOyiHDfQ4N5rVCWmniDEznt0/dtrMwPNd5JUR1FNQTDgWGN8VOJpG3BnSQUIE
# wVztOhbeA9jIdvohwpMl/KbVKlBl+BM74jJ5RF8CgYEAu+hJFe9jurH66ximaZmL
# Ps8PsnNWmWaXTZtkW8NWHB4uurNAa7oKWKt7iGcmHW4H/dbg5Q5I7y++xpsIT7as
# FhTwxOkxuyd+baxJtYbZk5VQhdymaesoEqEK+U+sxmDNSi0jcdIpnGPzDM2yS7dm
# uC8ES2I7MtdX5rh9zgRHMPMCgYEAjgR57EEFp312CG3HsMIc+e6X+Pr8WEZvy9LV
# ZQxTZGE5eO1vV+qtXlYwoxYgBy9UgfG3zE6WGLUfXQo2e63zGuXGK9einJPg1V5S
# f7KMrcloFM2vSj2xsPc0Y7Py7hb7NB/Hu18ZU4Xf368WMEc93JdQONuwDqZXOcj8
# /hQIq5UCgYBsjLpJ/EvkxXrCn5FxQVhZblKaGin2MzS0dRCeT4cLag/cisEnsZin
# Gofyqmc4vytMdacxly9c4376XG+xZYOtw9AHRtlW6nKX/DIVltrRWAd0C/rO+9vf
# r+KJoGkXJkC1x1gSliGr9lJJ0FrJiFH42ZzHnZTisPNdY+hbhRhgNw==
# -----END RSA PRIVATE KEY-----

