# Generated by Django 5.1 on 2024-09-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_boat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='exact_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('All Day', 'All Day')], max_length=20),
        ),
    ]
