# Generated by Django 5.1 on 2024-09-19 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats_and_locations', '0002_remove_marina_description_alter_marina_lake'),
        ('reservations', '0004_reservation_exact_time_reservation_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('All Day', 'All Day')], max_length=200),
        ),
        migrations.CreateModel(
            name='FloatPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('return_time', models.TimeField()),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('guests', models.TextField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats_and_locations.boat')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='float_plan', to='reservations.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
