# Generated by Django 5.1.5 on 2025-01-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_reservation_status_reservation_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='float_plan_pdf',
            field=models.FileField(blank=True, null=True, upload_to='float_plans/'),
        ),
    ]
