# Generated by Django 5.2.3 on 2025-10-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_join'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
